/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author User
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
    }

    private void clearForm() {
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
        
        buttonGroup1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        perempuanRadioButton = new javax.swing.JRadioButton();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();
        jenisKelaminAlert = new javax.swing.JLabel();
        statusAlert = new javax.swing.JLabel();
        prodiAlert = new javax.swing.JLabel();
        namaAlert = new javax.swing.JLabel();
        nimAlert = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Prodi");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki-Laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");
        aktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifCheckBoxActionPerformed(evt);
            }
        });

        kirimButton.setBackground(new java.awt.Color(0, 153, 153));
        kirimButton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        jenisKelaminAlert.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        statusAlert.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        prodiAlert.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        namaAlert.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        nimAlert.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aktifCheckBox)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(perempuanRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                            .addComponent(lakiLakiRadioButton))
                        .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimAlert)
                            .addComponent(namaAlert)
                            .addComponent(prodiAlert)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(statusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jenisKelaminAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(kirimButton)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(namaAlert)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nimAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prodiAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perempuanRadioButton)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenisKelaminAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktifCheckBox)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kirimButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:

        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = lakiLakiRadioButton.isSelected() ? "Laki-laki" : (perempuanRadioButton.isSelected() ? "Perempuan" : "");
        boolean isActive = aktifCheckBox.isSelected();

        boolean error = false;
        boolean cekNim = false;
        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                cekNim = true;
                break;
            }
        }

        namaAlert.setText("");
        nimAlert.setText("");
        prodiAlert.setText("");
        jenisKelaminAlert.setText("");
        statusAlert.setText("");

        if (nama.isEmpty()) {
            namaAlert.setText("Nama tidak boleh kosong!");
            namaAlert.setForeground(Color.red);
            error = true;
        } else if (!nama.matches("[a-zA-Z\\s]+")) {
            namaAlert.setText("Nama hanya boleh berisi huruf!");
            namaAlert.setForeground(Color.red);
            error = true;
        }

        if (nim.isEmpty()) {
            nimAlert.setText("NIM tidak boleh kosong!");
            nimAlert.setForeground(Color.red);
            error = true;
        } else if (!nim.matches("\\d+")) {
            nimAlert.setText("NIM harus berupa angka!");
            nimAlert.setForeground(Color.red);
            error = true;
        } else if (cekNim) {
            nimAlert.setText("Mahasiswa dengan " + nim + " sudah terdaftar");
            nimAlert.setForeground(Color.red);
            error = true;
        }

        if (prodi == null || prodi.isEmpty()) {
            prodiAlert.setText("Prodi harus dipilih!");
            prodiAlert.setForeground(Color.red);
            error = true;
        }

        if (jenisKelamin.isEmpty()) {
            jenisKelaminAlert.setText("Jenis kelamin harus dipilih!");
            jenisKelaminAlert.setForeground(Color.red);
            error = true;
        }

        if (!aktifCheckBox.isSelected()) {
            statusAlert.setText("Status harus dipilih!");
            statusAlert.setForeground(Color.red);
            error = true;
        }

            if (error) {
                return;
            }

            Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
            Mahasiswa.mahasiswas.add(mahasiswa);

            JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
            clearForm();
    }//GEN-LAST:event_kirimButtonActionPerformed
    
    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void aktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktifCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelaminAlert;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JLabel namaAlert;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimAlert;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JLabel prodiAlert;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel statusAlert;
    // End of variables declaration//GEN-END:variables
}
