/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class tambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form tambahDataPanel
     */
    public tambahDataPanel() {
        initComponents();
    }
    
    private void clearForm(){
        namaTextField.setText(" ");
        nimTextField.setText(" ");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
        
        buttonGroupJenisKelamin.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();
        namaAlert = new javax.swing.JLabel();
        nimAlert = new javax.swing.JLabel();
        prodiAlert = new javax.swing.JLabel();
        jenisKelaminAlert = new javax.swing.JLabel();
        statusAlert = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Prodi");

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        buttonGroupJenisKelamin.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki Laki");

        buttonGroupJenisKelamin.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        aktifCheckBox.setText("Aktif");
        aktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifCheckBoxActionPerformed(evt);
            }
        });

        kirimButton.setBackground(new java.awt.Color(0, 255, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        namaAlert.setText("namaAlert");

        nimAlert.setText("nimAlert");

        prodiAlert.setText("prodiAlert");

        jenisKelaminAlert.setText("jenisKelaminAlert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nimAlert)
                                    .addComponent(namaAlert)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiLakiRadioButton)
                                        .addGap(42, 42, 42)
                                        .addComponent(perempuanRadioButton))
                                    .addComponent(kirimButton)
                                    .addComponent(prodiAlert)
                                    .addComponent(jenisKelaminAlert)
                                    .addComponent(statusAlert))
                                .addGap(0, 87, Short.MAX_VALUE)))))
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(namaAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(nimAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodiAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(5, 5, 5)
                .addComponent(jenisKelaminAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAlert)
                .addGap(2, 2, 2)
                .addComponent(kirimButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void aktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktifCheckBoxActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText().trim();
        String nim = nimTextField.getText().trim();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = lakiLakiRadioButton.isSelected() ? "Laki-laki" : (perempuanRadioButton.isSelected() ? "Perempuan" : "");
        boolean isActive = aktifCheckBox.isSelected();

        boolean error = false;
        boolean cekNim = false;
        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                cekNim = true;
                break;
            }
        }

        namaAlert.setText("");
        nimAlert.setText("");
        prodiAlert.setText("");
        jenisKelaminAlert.setText("");
        statusAlert.setText("");

        if (nama.isEmpty()){
            namaAlert.setText("Nama tidak boleh kosong!");
            namaAlert.setForeground(Color.red);
            error = true;
        }else if (!nama.matches("[a-zA-Z\\s]+")) {
            namaAlert.setText("Nama hanya boleh berisi huruf!");
            namaAlert.setForeground(Color.red);
            error = true;
        }

        if(nim.isEmpty()){
            nimAlert.setText("NIM tidak boleh kosong!");
            nimAlert.setForeground(Color.red);
            error = true;
        }else if(!nim.matches("\\d+")){
            nimAlert.setText("NIM harus berupa angka!");
            nimAlert.setForeground(Color.red);
            error = true;
        }else if (cekNim) {
            nimAlert.setText("Mahasiswa dengan "+ nim + " sudah terdaftar");
            nimAlert.setForeground(Color.red);
            error = true;
        }

        if (prodi == null || prodi.isEmpty()) {
            prodiAlert.setText("Prodi harus dipilih!");
            prodiAlert.setForeground(Color.red);
            error = true;
        }

        if (jenisKelamin.isEmpty()) {
            jenisKelaminAlert.setText("Jenis kelamin harus dipilih!");
            jenisKelaminAlert.setForeground(Color.red);
            error = true;
        }
//        if (!statusCheckBox.isSelected()) {
//            statusAlert.setText("Status harus dipilih!");
//            statusAlert.setForeground(Color.red);
//            error = true;
//        }

        if (error) {
            return;
        }


        Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
        Mahasiswa.mahasiswas.add(mahasiswa);
        
        JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
        clearForm();
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.ButtonGroup buttonGroupJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelaminAlert;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JLabel namaAlert;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimAlert;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JLabel prodiAlert;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel statusAlert;
    // End of variables declaration//GEN-END:variables
}
